bashtian22

diff --git a/.github/workflows/iac.yml b/.github/workflows/iac.yml
--- a/.github/workflows/iac.yml
+++ b/.github/workflows/iac.yml
@@ -1,7 +1,201 @@
-# Workflow Name
+# # Workflow Name
+# name: "infra-gitops"
+
+# # Workflow Triggers
+# on:
+#   push:
+#     branches:
+#       - main
+#     paths:  
+#       - terraform/**
+#       - 'ansible/**'
+#   workflow_dispatch: # Enables manual trigger for destroy job
+
+# # Environment Variables
+# env:
+#   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#   S3_BUCKET: ${{ secrets.BUCKET }}
+#   AWS_REGION: ${{ vars.AWS_REGION }}
+#   EKS_CLUSTER: ${{ vars.EKS_CLUSTER }}
+
+# # Define Jobs
+# jobs:
+#   terraform:
+#     name: "Deploy Infra with Terraform on AWS"
+#     runs-on: ubuntu-latest
+#     # Run only on push events
+#     if: github.event_name == 'push'  
+
+#     defaults:
+#       run:
+#         shell: bash
+#         working-directory: ./terraform
+
+#     steps:
+#       - name: Checkout source code
+#         uses: actions/checkout@v4
+
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v3
+
+#       - name: Terraform init
+#         id: init
+#         run: terraform init -backend-config="bucket=$S3_BUCKET"
+
+#       - name: Terraform validate
+#         id: validate
+#         run: terraform validate
+
+#       - name: Terraform plan
+#         id: plan
+#         run: terraform plan -no-color -input=false -out planfile
+#         continue-on-error: true
+
+#       - name: Terraform plan status
+#         if: steps.plan.outcome == 'failure'
+#         run: exit 1
+
+#       - name: Terraform apply
+#         id: apply
+#         run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+
+#       - name: Configure AWS credentials
+#         uses: aws-actions/configure-aws-credentials@v4
+#         with:
+#           aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
+#           aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
+#           aws-region: ${{ env.AWS_REGION }}
+
+#       - name: Get Kubernetes config
+#         id: getconfig
+#         if: steps.apply.outcome == 'success'
+#         run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} 
+
+#       - name: Install Ingress controller
+#         if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
+#         run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0-beta.0/deploy/static/provider/aws/deploy.yaml
+  
+
+#   install_tools:
+#     name: "Install DevOps Tools via Ansible"
+#     runs-on: ubuntu-latest
+#     needs: terraform  
+#     if: github.event_name == 'push'
+
+#     steps:
+#       - name: Checkout source code
+#         uses: actions/checkout@v4
+
+#       - name: Configure AWS credentials
+#         uses: aws-actions/configure-aws-credentials@v4
+#         with:
+#           aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
+#           aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
+#           aws-region: ${{ env.AWS_REGION }}
+
+#       - name: Get Kubernetes config
+#         run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
+
+#       - name: Setup Python
+#         uses: actions/setup-python@v4
+#         with:
+#           python-version: '3.10'
+
+#       - name: Install Ansible and K8s dependencies
+#         run: |
+#           pip install ansible kubernetes PyYAML
+
+#       - name: Install Helm
+#         uses: azure/setup-helm@v3
+#         with:
+#           version: 'v3.12.0'
+#         env:
+#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
+
+#       - name: Run Ansible Playbook
+#         run: |
+          
+#           ansible-playbook ansible/install_tools.yml
+
+
+#   destroy:
+#     name: "Destroy Infra on AWS"
+#     runs-on: ubuntu-latest
+#     # Only trigger for workflow_dispatch
+#     if: github.event_name == 'workflow_dispatch'
+
+#     defaults:
+#       run:
+#         shell: bash
+#         working-directory: ./terraform
+
+#     steps:
+#       - name: Checkout source code
+#         uses: actions/checkout@v4
+
+#       - name: Setup Terraform
+#         uses: hashicorp/setup-terraform@v3
+
+#       - name: Terraform init
+#         id: init
+#         run: terraform init -backend-config="bucket=$S3_BUCKET"
+      
+#       - name: Configure AWS credentials
+#         uses: aws-actions/configure-aws-credentials@v4
+#         with:
+#           aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
+#           aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
+#           aws-region: ${{ env.AWS_REGION }}
+
+#       - name: Get Kubernetes config
+#         id: getconfig
+#         run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} 
+
+#       - name: Delete Ingress controller
+#         run: kubectl delete -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0-beta.0/deploy/static/provider/aws/deploy.yaml
+
+#       - name: Empty ECR Repository
+#         run: |
+#           REPOSITORY_NAME=${{ vars.ECR_REPO }}
+#           IMAGES=$(aws ecr list-images --repository-name $REPOSITORY_NAME --query 'imageIds[*]' --output json)
+#           if [[ "$IMAGES" != "[]" ]]; then
+#             echo "Deleting images from $REPOSITORY_NAME..."
+#             aws ecr batch-delete-image --repository-name $REPOSITORY_NAME --image-ids "$IMAGES"
+#           else
+#             echo "No images found in $REPOSITORY_NAME."
+#           fi
+      
+#       - name: Terraform destroy
+#         id: destroy
+#         run: terraform destroy -auto-approve -input=false
+
+
+#         ###hellooooo
+#         ##hello  
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
 name: "infra-gitops"
 
-# Workflow Triggers
 on:
   push:
     branches:
@@ -9,9 +203,8 @@ on:
     paths:  
       - terraform/**
       - 'ansible/**'
-  workflow_dispatch: # Enables manual trigger for destroy job
+  workflow_dispatch: 
 
-# Environment Variables
 env:
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -19,12 +212,10 @@ env:
   AWS_REGION: ${{ vars.AWS_REGION }}
   EKS_CLUSTER: ${{ vars.EKS_CLUSTER }}
 
-# Define Jobs
 jobs:
   terraform:
     name: "Deploy Infra with Terraform on AWS"
     runs-on: ubuntu-latest
-    # Run only on push events
     if: github.event_name == 'push'  
 
     defaults:
@@ -52,10 +243,6 @@ jobs:
         run: terraform plan -no-color -input=false -out planfile
         continue-on-error: true
 
-      - name: Terraform plan status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
-
       - name: Terraform apply
         id: apply
         run: terraform apply -auto-approve -input=false -parallelism=1 planfile
@@ -72,10 +259,24 @@ jobs:
         if: steps.apply.outcome == 'success'
         run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} 
 
+      # ==========================================
+      # Ingress
+      # ==========================================
+      - name: Setup SSH Tunnel for Ingress
+        if: steps.apply.outcome == 'success'
+        run: |
+          echo "${{ secrets.BASTION_SSH_KEY }}" > bastion_key.pem
+          chmod 400 bastion_key.pem
+          
+          CLUSTER_URL=$(terraform output -raw cluster_endpoint | sed 's/https:\/\///')
+         
+          ssh -i bastion_key.pem -o StrictHostKeyChecking=no -f -N -L 8443:$CLUSTER_URL:443 ubuntu@3.226.241.153
+          
+          kubectl config set-cluster "$(kubectl config current-context)" --server=https://localhost:8443 --insecure-skip-tls-verify=true
+
       - name: Install Ingress controller
         if: steps.apply.outcome == 'success' && steps.getconfig.outcome == 'success'
         run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0-beta.0/deploy/static/provider/aws/deploy.yaml
-  
 
   install_tools:
     name: "Install DevOps Tools via Ansible"
@@ -97,6 +298,20 @@ jobs:
       - name: Get Kubernetes config
         run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }}
 
+      # ==========================================
+      # 
+      # ==========================================
+      - name: Setup SSH Tunnel for Ansible
+        run: |
+          echo "${{ secrets.BASTION_SSH_KEY }}" > bastion_key.pem
+          chmod 400 bastion_key.pem
+          
+          CLUSTER_URL=$(aws eks describe-cluster --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} --query "cluster.endpoint" --output text | sed 's/https:\/\///')
+          
+          ssh -i bastion_key.pem -o StrictHostKeyChecking=no -f -N -L 8443:$CLUSTER_URL:443 ubuntu@3.226.241.153
+          
+          kubectl config set-cluster "$(kubectl config current-context)" --server=https://localhost:8443 --insecure-skip-tls-verify=true
+
       - name: Setup Python
         uses: actions/setup-python@v4
         with:
@@ -115,14 +330,11 @@ jobs:
 
       - name: Run Ansible Playbook
         run: |
-          
           ansible-playbook ansible/install_tools.yml
-
 
   destroy:
     name: "Destroy Infra on AWS"
     runs-on: ubuntu-latest
-    # Only trigger for workflow_dispatch
     if: github.event_name == 'workflow_dispatch'
 
     defaults:
@@ -152,6 +364,17 @@ jobs:
         id: getconfig
         run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} 
 
+      # ==========================================
+      # 
+      # ==========================================
+      - name: Setup Tunnel for Destroy
+        run: |
+          echo "${{ secrets.BASTION_SSH_KEY }}" > bastion_key.pem
+          chmod 400 bastion_key.pem
+          CLUSTER_URL=$(aws eks describe-cluster --name ${{ env.EKS_CLUSTER }} --region ${{ env.AWS_REGION }} --query "cluster.endpoint" --output text | sed 's/https:\/\///')
+          ssh -i bastion_key.pem -o StrictHostKeyChecking=no -f -N -L 8443:$CLUSTER_URL:443 ubuntu@3.226.241.153
+          kubectl config set-cluster "$(kubectl config current-context)" --server=https://localhost:8443 --insecure-skip-tls-verify=true
+
       - name: Delete Ingress controller
         run: kubectl delete -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.12.0-beta.0/deploy/static/provider/aws/deploy.yaml
 
@@ -160,16 +383,9 @@ jobs:
           REPOSITORY_NAME=${{ vars.ECR_REPO }}
           IMAGES=$(aws ecr list-images --repository-name $REPOSITORY_NAME --query 'imageIds[*]' --output json)
           if [[ "$IMAGES" != "[]" ]]; then
-            echo "Deleting images from $REPOSITORY_NAME..."
             aws ecr batch-delete-image --repository-name $REPOSITORY_NAME --image-ids "$IMAGES"
-          else
-            echo "No images found in $REPOSITORY_NAME."
           fi
       
       - name: Terraform destroy
         id: destroy
         run: terraform destroy -auto-approve -input=false
-
-
-        ###hellooooo
-        ##hello
